/** @format */

import Header from "@/components/Layout/Header/Header"
import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import styles from "../components/Layout/Layout.module.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Pedro Ferreira - Porfolio",
  description: "Generated by create next app",
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className={styles.main}>{children}</main>
      </body>
    </html>
  )
}
